### ISSUE TITLE
Support multiple pages in the same HAR

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#10]
A HAR file can contain multiple pages in the same file in the specification (WPT uses that when you choose to download the HAR and made more than one run if I remember correctly). We need to decide how to handle that.

**Comment by micmro** [comment]
In the moment I only read the first page. I was thinking the easiest solution would be to add a dropdown to select them. This could be combine with the #2 to compare different pages with each other.

If someone wants to show them after each other (s)he could simply instantiate one for each page in a simple loop.

**Comment by soulgalore** [comment]
Sounds good!
