### ISSUE TITLE
Support more timings in the HAR

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#11]
The HAR spec has onLoad an onContentLoad specified in the pageTimings element. The HAR spec is old and we know today that there are other metrics that are (more) interesting. WebPageTest adds startRender in the timings with an underscore like this:

``` javascript
 "pageTimings": {
          "onLoad": 557,
          "onContentLoad": -1,
          "_startRender": 449
 },
```

Maybe we should generate vertical lines for all keys in pageTimings, then we are open to put other timings in there and automatically get them in our HAR?

**Comment by soulgalore** [comment]
@micmro you alreay fixed this right? seems to work for me :)

**Comment by micmro** [comment]
Youp i did. Forgot to mention it in the issue.
2016. 2. 3. 오후 4:07에 "Peter Hedenskog" notifications@github.com님이 작성:
