### ISSUE TITLE
Font size is too large https://micmro.github.io/PerfCascade/

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#115]
I think something broke with the last changes, I maybe can have look tonight of someone else doesn't beat me to it:

<img width="884" alt="screen shot 2017-01-12 at 08 28 58" src="https://cloud.githubusercontent.com/assets/540757/21880818/380c4618-d8a1-11e6-9f99-8b41af0321e4.png">

**Comment by micmro** [comment]
I can quickly fix it - I think I know what it is.

**Comment by micmro** [comment]
fixed

**Comment by soulgalore** [comment]
thanks for fixing so fast :)
