### ISSUE TITLE
Simplify build steps to make SemVer releases

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#116]
Currently `npm run release` already handles the tagging and releasing automatically but only increments the _patch_ version. 
It would be good to play nice with npm and have some automated way of also releasing Major and Minor versions - e.g. `npm run release --major` or at least `npm run release-major`. It could parse the version number and update it based on the release.

`1.2.3`-> major -> `2.0.0`
`1.2.3`-> minor -> `1.3.0`
`1.2.3`-> patch -> `1.2.4`

**Comment by soulgalore** [comment]
Thinking at the same time we could add CHANGELOG.md? There's been so many changes/fixes lately and I have a hard time following what's released when :)

**Comment by micmro** [comment]
Makes sense 👍

**Comment by micmro** [comment]
SemVer will be addressed via #99

**Comment by micmro** [comment]
Created #137 to track the change-log work
