### ISSUE TITLE
Highlight HTTP/2 server push

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#119]
In HARs from WebPageTest the response get the extra field <code>_was_pushed</code> with the value of 1, for Browsertime we do the same for HARs from Chrome (not in FF but that would be nice to fix).  

Right now we show that like this:
<img width="828" alt="screen shot 2017-01-14 at 21 59 24" src="https://cloud.githubusercontent.com/assets/540757/21958053/ce3b98e6-daa4-11e6-9086-a86b69eebfa4.png">

But push will be more and more commons I think it would be great to show that directly in the waterfall. Should we have a specific color on that line or should we invent a push symbol? What do you think @micmro and @tobli ?

**Comment by tobli** [comment]
Agreed, it would be a nice addition. Colours are a bit opaque, IMHO. Maybe we can think of something else altogether, like a ➡ symbol in the waterfall, just left of the bar?

**Comment by soulgalore** [comment]
I'll look for a good symbol tonight.

**Comment by micmro** [comment]
Sounds good.
I wonder if we can overlay the push icons over the mine-type or so to save some space, but I suppose it's not more space than the warning symbol anyway so it should be fine on it's own.

**Comment by tobli** [comment]
Actually I was thinking of having something within the graph area to the right (since the push is sort of a variant of the client initiated connect/send phase)

**Comment by soulgalore** [comment]
For me having one to the left where we have warnings today would be ok for now? First check for push, then the warnings?

**Comment by soulgalore** [comment]
I've got a problem getting <code>$ npm run watch</code> working clean on my local, seems changes to .git is picked up and sometimes I (at least) get the feeling that changes aren't populated, so I couldn't add an example of the push symbol (added just an arrow). Have @micmro got the same or does it work cleanly for you? I can test more tonight.

Adding the prepared icon here for now, see if it works.
<code>
 <path d="m 16.556818,9 q 0,0.554578 -0.379974,0.934489 L 9.4913511,16.62 Q 9.0908356,17 8.5568178,17 8.0330667,17 7.6325511,16.62 L 6.8623378,15.849778 q -0.3902489,-0.390222 -0.3902489,-0.934489 0,-0.544267 0.3902489,-0.934578 l 3.0089866,-3.008978 -7.2297866,0 Q 2.10752,10.971733 1.77376,10.586667 1.44,10.201511 1.44,9.657244 l 0,-1.3144884 Q 1.44,7.7984889 1.77376,7.4133333 2.10752,7.0282667 2.6415378,7.0282667 l 7.2297866,0 L 6.8623378,4.0089778 Q 6.4720889,3.6392889 6.4720889,3.0847111 q 0,-0.5545778 0.3902489,-0.9242667 L 7.6325511,1.3902222 Q 8.0228,1 8.5568178,1 9.1011022,1 9.4913511,1.3902222 L 16.176844,8.0757333 Q 16.556818,8.4352 16.556818,9 Z" />
</code>

**Comment by soulgalore** [comment]
Ok, I had problem with the new automatic linting. Let me test it a little more and add a screenshot.

**Comment by soulgalore** [comment]
Yep, could be they push too much:
https://www.filamentgroup.com/lab/modernizing-delivery.html
<img width="1265" alt="screen shot 2017-01-16 at 21 05 17" src="https://cloud.githubusercontent.com/assets/540757/21997439/aac81f06-dc2f-11e6-9619-589da1811b5e.png">

**Comment by micmro** [comment]
I don't have a problem with this - are you on mac linux or windows? Perhaps you can try to clean your `npm_modules` folder and re-install the dependencies?

Great work - looks brilliant, I just have just two small suggestions: 
- Usually client-server diagrams have the server on the right, I wonder if it makes more semantic sense to turn the arrow by 180°?
- I wonder if the icons are a bit visually strong and seem to overpower the other icons, should we make them a bit thinner, or make the colour lighter to make them less dominant?

**Comment by soulgalore** [comment]
Yep I run on Mac, let me when I get the problem again I'll create a new issue and add some log.

I can change the arrow, let me think about it.

Let me make it a little smaller and we can have a look. Let me see if we can find another site also with some warnings, right now it's just adds the icon to the icon list so if we have warnings or other content info, they should have the aprox same size to look good?

**Comment by soulgalore** [comment]
Little smaller, yep I agree looks better:
<img width="1226" alt="screen shot 2017-01-17 at 06 00 57" src="https://cloud.githubusercontent.com/assets/540757/22008318/63d1595a-dc7a-11e6-9ea4-5854f1e61a34.png">

And even smaller (that the one that is in this PR right now):
<img width="1228" alt="screen shot 2017-01-17 at 06 06 51" src="https://cloud.githubusercontent.com/assets/540757/22008429/73dace20-dc7b-11e6-84a3-e9e72856178e.png">

And to the left:
<img width="1223" alt="screen shot 2017-01-17 at 06 03 49" src="https://cloud.githubusercontent.com/assets/540757/22008357/cefb2526-dc7a-11e6-9ce6-6bbcd4471fbb.png">

**Comment by micmro** [comment]
Nice, looks really good 🏆 . 

Could you find some left or right references? I have a slight preference for left due to the semantics, but can live well with either :).

**Comment by tobli** [comment]
I'm not too concerned about left to right. Every other graphic is based on the response, right?

**Comment by tobli** [comment]
![push](https://cloud.githubusercontent.com/assets/540266/22011927/cc10ef46-dc91-11e6-9443-2575bf850331.jpg)

This is roughly my idea for moving the push arrow closer to where the server actually issues the push. Saves space to the left, and maybe makes slightly more semantical sense. The arrow is slightly lighter as well.

**Comment by tobli** [comment]
I'll close this now, since cb0a214 is released. The mockup for a moved arrow is here for future reference.
