### ISSUE TITLE
Handle .zhar files

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#12]
Would be cool to also be able to handle zipped HAR files (http://www.softwareishard.com/blog/har-12-spec/ HAR compression), some HAR files are quite big.

**Comment by micmro** [comment]
Looks like this i just a gzipped HAR with the extension changed to `*.zhar`.

Some options for client side inflation:
- https://github.com/dankogai/js-deflate/blob/master/rawinflate.js
- https://github.com/nodeca/pako/blob/master/dist/pako_deflate.min.js

**Comment by micmro** [comment]
zHAR Support added in demo page as well.
