### ISSUE TITLE
Lint imports spacing

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#122]
Find way we can keep imports in a similar style:
e.g.: 
`import { roundNumber } from "../helpers/misc";`
vs
`import {roundNumber} from "../helpers/misc";`

Similar to [`object-curly-spacing`](http://eslint.org/docs/rules/object-curly-spacing) in ES-lint.

Found only [`import-spacing`](https://palantir.github.io/tslint/rules/import-spacing/) but it does not handle the

**Comment by tobli** [comment]
We could add https://github.com/buzinas/tslint-eslint-rules, which has object-curly-spacing.
