### ISSUE TITLE
Icon for 204 No content

### ISSUE THREAD

**Issue by tobli** [micmro/PerfCascade#124]
Currently 204 replies (which naturally lacks a content type) are rendered with the question mark "other" icon. This is somewhat misleading, and a better option would be a separate icon for this purpose.

**Comment by soulgalore** [comment]
I agree, let see if we can find one that is ok: http://fontawesome.io/icons/

**Comment by soulgalore** [comment]
@tobli added the plain text icon for this, that's cool

**Comment by tobli** [comment]
"Good enough for now, safe enough to try" =)
