### ISSUE TITLE
Icons can push asset names too far

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#129]
We should think about how we can make sure that the waterfall looks good if we get multiple icons for row. If you set the width of the waterfall, turn on content icons and indicator icons we will have different space for the name of the asset depending what kind responses we have.

In the examples we have the same width but for the first one, the reponses has no indicator icons = much space to write the name of the request:
<img width="317" alt="screen shot 2017-01-18 at 10 14 57" src="https://cloud.githubusercontent.com/assets/540757/22057887/03ab4d68-dd67-11e6-9ddd-e3804ae96499.png">

Here we have two indicator icons = some names goes outside of the name space
<img width="514" alt="screen shot 2017-01-18 at 10 14 21" src="https://cloud.githubusercontent.com/assets/540757/22057889/05421864-dd67-11e6-97d5-f52a255c6521.png">

**Comment by soulgalore** [comment]
This will be fixed in #145

**Comment by micmro** [comment]
Sorry not yet - it still renders 2 icons - will create a new PR to fix this.

**Comment by micmro** [comment]
ok now fixes via #145
