### ISSUE TITLE
Initial request (undefined after page request started)

### ISSUE THREAD

**Issue by Janpot** [micmro/PerfCascade#130]
The first entry has `(undefined after page request started)` for `Started`

<img width="734" alt="screen shot 2017-01-18 at 18 18 26" src="https://cloud.githubusercontent.com/assets/2109932/22075011/a703b0e8-ddaa-11e6-9a69-1b3ec97aa9a2.png">

**Comment by Janpot** [comment]
Getting really impressed here with how fast issues get resolved in this repo! 👍

**Comment by tobli** [comment]
Thanks! As a matter of fact, I'm actually working on a fix for that already. =)

**Comment by micmro** [comment]
released via `v0.2.23`

**Comment by soulgalore** [comment]
Oh sorry @tobli I missed assigning to me one minute after I marked it as a bug
