### ISSUE TITLE
Round off timings from Chrome Har files

### ISSUE THREAD

**Issue by Janpot** [micmro/PerfCascade#134]
Might want to round off to a few decimals in the panels. Exact value would still be viewable in RawData.

<img width="292" alt="screen shot 2017-01-19 at 05 26 10" src="https://cloud.githubusercontent.com/assets/2109932/22093684/f31e535e-de07-11e6-87ba-3fcf5f10dc28.png">

<img width="298" alt="screen shot 2017-01-19 at 05 26 23" src="https://cloud.githubusercontent.com/assets/2109932/22093691/f80d5144-de07-11e6-80ac-1ba31ff59f0e.png">

**Comment by soulgalore** [comment]
Would be cool to file a bug to Chrome too if there's isn't one already, that kind of precision cannot be right :)

**Comment by Janpot** [comment]
I think they use high resolution timers for this. High precision should be expected. Looks like 4 digits are meaningful, the rest is the result of floating point arithmetic.

**Comment by micmro** [comment]
@tobli are you working on this? If not I can do a quick fix (perhaps have it as a `<abbr>` and have the full precision as `title`).

**Comment by tobli** [comment]
Oh, sorry. Feel free to go ahead. I have a fix, but part of a bunch of changes in a branch I haven't pushed yet.

**Comment by micmro** [comment]
No worries. I'll wait for your PR then.

**Comment by tobli** [comment]
This is included in #141 (rounding to at most 3 decimals). I think it's ok to cut off at 3 and drop the rest. Testing High performance timer (performance.now()) in Safari and Chrome, I don't get more that microsecond precision anyway.
