### ISSUE TITLE
Some style nits

### ISSUE THREAD

**Issue by Janpot** [micmro/PerfCascade#142]
Some suggestions I've been collecting over the few weeks I've been using this library (really loving it so far):

1. Use a nicer icon for close button like: ✕ (U+2715).
![screen shot 2017-02-07 at 17 17 28](https://cloud.githubusercontent.com/assets/2109932/22744404/92d379cc-ee1d-11e6-9830-51ca9ab6744d.png)

2. Use pointer cursor for the rows to indicate they're clickable
![cursor](https://cloud.githubusercontent.com/assets/2109932/22744592/129412a2-ee1e-11e6-8168-984350853870.png)
Also, the tabs "General", "Request",... don't have a pointer cursor.

3. make the `<h3>` in the details view an anchor tag, so it's easier to navigate to it directly and easier to copy with "Copy Link Address"

4. Sometimes the contrast between text color and background color make tab titles hard to read
![screen shot 2017-02-08 at 16 39 27](https://cloud.githubusercontent.com/assets/2109932/22744745/96322bd0-ee1e-11e6-9e9e-49d211059d7b.png)

**Comment by Janpot** [comment]
@micmro adding another one here about the 'Raw Data' tab.

![screen shot 2017-02-17 at 09 53 08](https://cloud.githubusercontent.com/assets/2109932/23058825/0ba0c24e-f4f7-11e6-848d-0b8c6d087c7c.png)

It would look better with a `width: 100%`
also, the white margins would look better if they had the same color as the `<pre>`:

![screen shot 2017-02-17 at 09 57 44](https://cloud.githubusercontent.com/assets/2109932/23058941/9262027a-f4f7-11e6-9b81-3e944a2d54b2.png)

**Comment by micmro** [comment]
Thanks for the feedback. Some really good ideas.

Only _4._ looks like an issue with your local CSS. It seems you give your `button`s a colour in a very specific CSS selector. I've given it a higher specificity as part of the link anyway so perhaps it'll be fix this way.

**Comment by soulgalore** [comment]
Wow great changes! One thing about the raw tab: The HAR file can contain HTML in the text element (I can add a link to an example later today) and that HTML will run in the raw tab as it is now and if it is inline CSS, it can change the look and feel of the page.

**Comment by soulgalore** [comment]
Let me create a separate issue for that :)

**Comment by Janpot** [comment]
@micmro Strange, my page only has a handful other style rules. Could it be that on the demo page there's a css reset that sets button color to `inherit` and cursor to `pointer`?

![screen shot 2017-02-17 at 14 26 25](https://cloud.githubusercontent.com/assets/2109932/23066937/4482dffe-f51d-11e6-8d65-64b4b0d47206.png)

**Comment by micmro** [comment]
Right, I use CSS normalizer in both the preview and the demo page - was not aware that buttons do not inherit the colour by default (learn something new every day :)). Should be fixed with this PR then.

**Comment by Janpot** [comment]
Not sure you want to go that route, but it should be possible with a preprocessor to scope normalize.css to `.water-fall-chart` and add the result to `perf-cascade.css`. seems like they do a similar thing here: https://github.com/dperrymorrow/markdown-css/blob/master/src/scoped-normalize.less

**Comment by micmro** [comment]
I had thought about this in the beginning of the project, but decided that most project use some reset anyway - I also wanted to keep the styles as simple and easily over-writable as possible.
So I don't fancy adding a scoped reset too much. However I tried the current PR without the normalizer in chrome and FF and it looks fine - I might remove it for the dev-version to ensure we stay (relatively) reset-safe.

**Comment by Janpot** [comment]
👍  totally reasonable

**Comment by micmro** [comment]
released with `v0.5.0`
