### ISSUE TITLE
Tab for issues

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#145]
In order to only show one warning icon (#129) it would be useful to show all warnings in a tab in the details view.

**Comment by tobli** [comment]
Yes, I've been thinking about this too. Maybe put it in the General tab, that way it's instantly available. There shouldn't be more than a handful of warnings anyway per resource.

**Comment by soulgalore** [comment]
I like that too. If we could move http push so it is inline to the right of the bar (like wpt display error code for 302 etc) then it would be perfect.

**Comment by micmro** [comment]
Got a prototype with a separate tab working (see branch 145). But it will be better in the general tab. Will do so later.

As part of this I also moved the indicator scanning logic to parse time as preparation for #56 and others.

**Comment by tobli** [comment]
Great

**Comment by micmro** [comment]
Updated - see PR
<img width="752" alt="screen shot 2017-02-12 at 9 49 40 pm" src="https://cloud.githubusercontent.com/assets/1680390/22862180/31bbfee0-f16d-11e6-848e-ad5ec7b61ed7.png">

**Comment by micmro** [comment]
released via v0.4.0
