### ISSUE TITLE
HTML/CSS inside of the HAR can change the look and feel of PerfCascade

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#149]
You can include HTML/CSS in the HAR, it built in HAR Export for Firefox. 

Here's an example HAR
https://gist.github.com/soulgalore/bd8491624657f6092db31f4e5343556e

And when I click on the first request, the background color is changed:
<img width="1404" alt="screen shot 2017-02-17 at 14 15 02" src="https://cloud.githubusercontent.com/assets/540757/23066598/ada4c648-f51b-11e6-9add-2f91c46dc27a.png">

**Comment by soulgalore** [comment]
And we should make sure that you can view that inside of the raw data or maybe add a new tab. Right now the HTML is parsed.
<img width="1050" alt="screen shot 2017-02-17 at 14 17 42" src="https://cloud.githubusercontent.com/assets/540757/23066643/e9fd13b6-f51b-11e6-8162-f3042efa52b7.png">

**Comment by Janpot** [comment]
to make it completely XSS safe you should probably html escape every value that comes out of the HAR file
