### ISSUE TITLE
Create tab for `content` if present

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#154]
If the HAR entry contains a `content. text` entry we could show it as a dedicated tab.

- Pretty print it?
- Perhaps we could even have a preview i-frame for HTML?

**Comment by micmro** [comment]
One thing we would need to check if we go with the i-frame preview is possible security implications. It should be locked down with the [`sandbox`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) and [`csp`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/csp) attribute to not execute JS, submit forms etc.

**Comment by soulgalore** [comment]
For my use case its more to pretty print HTML so you can read it in an easy way. Or copy it.

**Comment by micmro** [comment]
Ah ok, that should be quite doable. We could do the same perhaps for CSS?

**Comment by micmro** [comment]
Got the tab working for all text/* based MIME types.
It currently prints the text as returned, but I think a pretty print for HTML etc would be nice as it's usually minified.

<img width="778" alt="Screen Shot 2019-05-26 at 11 17 26 AM" src="https://user-images.githubusercontent.com/1680390/58383705-e634d980-7fa7-11e9-95d4-909f3b8ae900.png">

**Comment by soulgalore** [comment]
Wow great @micmro ! It looks cool. I think one thing could be to add a new line after x chars if all content is on one line or something like that?

**Comment by soulgalore** [comment]
I've tested you branch just now @micmro, think it is great! This is much better than the current version. Do you feel ok to release it the coming days? I'm pushing a new release on Thursday this week where I wanna include it but no pressure, I'll do a fix release later on if you are busy :) Thanks a lot for the fix!

**Comment by micmro** [comment]
After doing some pretty-print research over the weekend I decided to only fixed the line-wrapping today. Will release it later.

Doing a pretty print is a bit more involved as I had anticipated and I don't want to bloat the code-base with a new dependency.
Let me know if you have some ideas.
