### ISSUE TITLE
Vary header and some other header might exist more than once

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#156]
We currently show only the fist `vary` response header in the Request summary, but it is possible that there are more than one (e.g. github demo page HAR).

Same for `Set-Cookie`.
<img width="371" alt="screen shot 2017-02-19 at 6 52 01 pm" src="https://cloud.githubusercontent.com/assets/1680390/23101595/86ccf71e-f6da-11e6-8598-9436d1ec84f0.png">

**Comment by staabm** [comment]
Another example for a header which can occur more then once is `Link` (http2 server push)

**Comment by micmro** [comment]
released with `v1.2.2`
