### ISSUE TITLE
Error in 0.6.0?

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#158]
I tried to upgrade to 0.6.0 in sitespeed.io but get an error, could something got wrong in the refactoring?

<img width="1440" alt="screen shot 2017-02-22 at 10 49 17" src="https://cloud.githubusercontent.com/assets/540757/23206093/a2f2aeb6-f8ec-11e6-8615-ce1c3dd7b011.png">

**Comment by micmro** [comment]
Oh, sorry that's possible - I'll look into it.

**Comment by micmro** [comment]
I could not find a regular HAR but after creating one with sitespeed (btw props for the nice nad simple docker container setup) I found the cupid:
I started to escape the tuple value, but there was a non-string in this value: `["Initiator Line", 0]`.

**Comment by micmro** [comment]
fixed with `v0.6.1`

**Comment by soulgalore** [comment]
ah sorry for not adding HAR, I just a had a couple of minutes and wanted to upgrade to run the latest and greatest version :). Thanks for the fix will upgrade tonight so we are ready for the next release!

**Comment by soulgalore** [comment]
and thanks for the kind words about Docker :) If you just wanna get a HAR, [Browsertime](https://github.com/sitespeedio/browsertime) (there's containers for that too) is perfect.
