### ISSUE TITLE
Render user-timing entries from WPT

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#164]
WPT includes user-timing markers in a non-standard way. It would be nice to extract and visualize those as well (perhaps with an option to toggle it).

`_firstPaint`, `_domContentLoadedEventStart` ... could be interesting as well.

```JSON
{
  "log": {
    "version": "1.1",
    "creator": {
      "name": "WebPagetest",
      "version": "2.18"
    },
    "pages": [
      {
       ...
        "_firstPaint": 2541,
        "_loadEventStart": 12124,
        "_loadEventEnd": 12505,
        "_fullyLoaded": 15766,
        "_domContentLoadedEventStart": 5058,
        "_domContentLoadedEventEnd": 5469,
        "_userTime.startTimer-headProcessing": 971,
        "_userTime.startTimer-visuallyComplete": 972,
        "_userTime.startTimer-beaconProcessing": 972,
        "_userTime.endTimer-beaconProcessing": 972,
        "_userTime.startTimer-atmInit": 973,
       ...
    }]
}
```

<img width="680" alt="screen shot 2017-02-25 at 2 04 47 pm" src="https://cloud.githubusercontent.com/assets/1680390/23328407/a208ab6c-fb63-11e6-9b38-37ef0edf317e.png">

**Comment by soulgalore** [comment]
I did some testing before to include them in sitespeed.io and when you got more than 3-4 user timings the waterfall didn't look so good (especially if they happens almost the same time). also have the problem with google ads sending 1000+ of timings for some sites. let me see if I can find some good example HAR files.

**Comment by micmro** [comment]
Hm, makes sense. Perhaps adding them with a toggle might work?
Or a threshold e.g. if `markerCount > requestCount/3` hide them or so.

**Comment by soulgalore** [comment]
I think WebPageTest shows one or two? Or maybe if we can show all User Timings starting by xxx?  Jonathan wrote about that [overloading of User Timings](https://www.sitespeed.io/usertimings-best-practices/).

**Comment by micmro** [comment]
I just have an example with 10+, so they only show up in the [customize waterfall](https://www.webpagetest.org/customWaterfall.php?test=170225_V1_bdaa5018fd99abc8a9cdea06f1f151ad&run=1&width=930) page.

I guess `_firstPaint`, `_loadEventStart`, `_loadEventEnd`, `_fullyLoaded` etc. could be useful either way.

**Comment by soulgalore** [comment]
For sitespeed.io we just put them in the timings field with starting with an underscore, I think WebPageTest do the same with some metrics? Else we could talk to Pat. 

Another idea is to have a table to show extra info (that you could opt in/out). And maybe something like the HAR viewer has:
<img width="924" alt="screen shot 2017-02-25 at 12 44 14" src="https://cloud.githubusercontent.com/assets/540757/23330810/3d5b94d2-fb58-11e6-916a-9ca2440f85ba.png">

I think that extra things will be super cool when/if we have the ability to compare HAR files.

**Comment by micmro** [comment]
added (mostly) via #184 in `v1.0.1`
