### ISSUE TITLE
A sample Har file does not show up correctly on PerfCascade

### ISSUE THREAD

**Issue by joychester** [micmro/PerfCascade#166]
my file works well on [Har viewer](http://www.softwareishard.com/har/viewer/), but not PerfCascade, please help to verify, FYI:
[sample.har.txt](https://github.com/micmro/PerfCascade/files/804101/sample.har.txt)

**Comment by tobli** [comment]
This is due to a "data:image/gif;base64,..." entry in the har. HAR viewer displays these as empty, 0ms, rows. However I'd argue that we should filter them out when parsing the HAR.
ping @micmro

**Comment by micmro** [comment]
Thanks @tobli. I agree, if we leave it in the waterfall gets a bit disjointed (see screenshot below) and I can't see a lot of value in keeping them in the HAR.
What do you think @soulgalore?

<img width="688" alt="screen shot 2017-03-01 at 3 43 40 pm" src="https://cloud.githubusercontent.com/assets/1680390/23448709/e839b2cc-fe95-11e6-9093-bd562706e301.png">

**Comment by soulgalore** [comment]
Agree we should remove them.

**Comment by micmro** [comment]
fixed with `v0.7.0`

**Comment by joychester** [comment]
Thanks All!! wow, Peter, nice to meet you again, @soulgalore , Perf Planet is small... :)

**Comment by joychester** [comment]
Can i reopen this Issue? as current release 0.8.0+ is failing on my har file again.. Thanks!

**Comment by soulgalore** [comment]
Is that the same file as you attached @joychester ? When I tried in Chrome that one worked for me? Can you check the console log what kind of error you get?

**Comment by joychester** [comment]
Oops, my fault, peter, uploaded a broken one..
