### ISSUE TITLE
Metric names are horizontal on Safari

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#167]
For Chrome it looks like this:
<img width="1024" alt="screen shot 2017-02-28 at 11 40 07" src="https://cloud.githubusercontent.com/assets/540757/23402206/e15d6642-fdaa-11e6-8c1b-5fa7f3bed266.png">
And on Safari:
<img width="997" alt="screen shot 2017-02-28 at 11 39 00" src="https://cloud.githubusercontent.com/assets/540757/23402210/e763b8de-fdaa-11e6-8ffc-5c3c1c5127eb.png">

**Comment by tobli** [comment]
FYI, this is not an issue in Safari Technology Preview (release 24 as of today). Might be an svg render issue that has been resolved.

**Comment by micmro** [comment]
Looks like IE Edge has the same issue (and a few others). Will have to setup my Windows VM again to test this in more detail. 

<img width="937" alt="edge vm" src="https://cloud.githubusercontent.com/assets/1680390/23496423/80c28ee4-ff61-11e6-8200-5087c15c42aa.png">

**Comment by micmro** [comment]
fixed with `v1.2.1`
