### ISSUE TITLE
Choose which HAR (page) to show in the API

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#168]
Today we have the options to choose what page to show with the *pageSelector* but we have a use case in sitespeed.io where we want to choose what page to start to show (default now is always the first one). We should add a extra option, to choose the exact page to show.

**Comment by micmro** [comment]
released with `v0.7.0`

**Comment by soulgalore** [comment]
Thanks for fixing this so fast! Pushing it in the next sitespeed.io release, this helps us so we can get rid of inlining the HAR if the pages are served by a server.
