### ISSUE TITLE
round numbers in the tooltips

### ISSUE THREAD

**Issue by Janpot** [micmro/PerfCascade#172]
Similar to https://github.com/micmro/PerfCascade/issues/134. Need to round the timings in the tooltips.

<img width="914" alt="screen shot 2017-03-04 at 21 40 22" src="https://cloud.githubusercontent.com/assets/2109932/23582126/bbc71136-0123-11e7-919e-99f0955edc55.png">

**Comment by micmro** [comment]
fixed with `v0.9.0`
