### ISSUE TITLE
Add event when HAR is finished loading/parsed?

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#174]
When we load large HAR files the loading and parsing can take some time so as a user it would be nice to use some kind of [loader](https://github.com/lukehaas/css-loaders) and when the HAR is ready, we could remove the loader (when the event is fired).

**Comment by micmro** [comment]
I'd see the uploading (technically it's not uploading but on the same machine anyway) as an external process that is not covered by PerfCascade. I could add a sample to the demo site though.

For the parsing part you could currently use the `perfCascade.transformHarToPerfCascade` to convert the HAR and the `perfCascade.fromPerfCascadeFormat` functions to render it.
@tobli was suggesting to to remove them with #128, so a callback would be required then.

**Comment by soulgalore** [comment]
Yes of course let me test how long time it takes to parse vs loading, if the load takes 99% then we don't need it. I'll re-open if needed.
