### ISSUE TITLE
Remove console logs

### ISSUE THREAD

**Issue by vic0707** [micmro/PerfCascade#180]
Great tool! 

Would it be possible to remove the logs that are output when a HAR is successfully displayed? (check attached print screen for example)

I think that it will make it cleaner to remove this.

Thanks
![screen shot 2017-03-13 at 10 41 19](https://cloud.githubusercontent.com/assets/18684987/23849037/1b49751a-07da-11e7-81c2-7a8e62ba0e0f.png)

**Comment by micmro** [comment]
fixed with `v1.0.0`
