### ISSUE TITLE
Expose css file in "style" field of package.json

### ISSUE THREAD

**Issue by vic0707** [micmro/PerfCascade#182]
Hello,

I am trying to import the css using ```sass-module-importer```. The importer documents the lookup strategy like this: 
```
1. Set a SCSS/Sass/CSS file on the "main" field of their package.json/bower.json
2. Set a SCSS/Sass/CSS file on the "style" field of their package.json/bower.json
3. Have a index.css file on the root of their module
```

Can this be adapted on  the ```style``` field on the ```package.json``` file.

Example here: https://github.com/twbs/bootstrap-sass/issues/1045

**Comment by micmro** [comment]
fixed with `v1.0.0`
