### ISSUE TITLE
[Feature] Add User custom metrics to SVG

### ISSUE THREAD

**Issue by joychester** [micmro/PerfCascade#183]
Can i have a way to pass some **custom metrics** overlay to SVG?
for example the **visualComplete time** (2.9 seconds marked in my attached SVG) will be added to waterfall chart , that will be useful to know when the user actually see the pages. i mocked a SVG here attached for your reference. Let me know if it is making sense to you. Thanks!!
<img width="1349" alt="screen shot 2017-03-16 at 12 11 19 am" src="https://cloud.githubusercontent.com/assets/235618/23958649/c01472f2-09dd-11e7-9aba-54c0c3de610c.png">

**Comment by soulgalore** [comment]
@joychester if you use sitespeed.io they are automatically added :) : 
<img width="986" alt="screen shot 2017-03-15 at 5 28 26 pm" src="https://cloud.githubusercontent.com/assets/540757/23959201/d7561c60-09a4-11e7-9332-8017e9b92450.png">

PerfCascade pickup all metrics inside of [pageTiminings](http://www.softwareishard.com/blog/har-12-spec/#pageTimings) that are named with a underscore, so if you add _lastVisualChange there it will automatically be picked up by PerfCascade.

Best
Peter

**Comment by soulgalore** [comment]
@joychester you can check out https://results.sitespeed.io/sitespeed-result/en.wikipedia.org/2017-03-15-17-00-03/pages/en.wikipedia.org/wiki/Barack_Obama/data/browsertime.har.gz as an example on how you can add it.

**Comment by joychester** [comment]
Thanks for the insights Peter, let me give it a try!

**Comment by soulgalore** [comment]
Let us add info in the README and close this issue.

**Comment by joychester** [comment]
i have verified from my side based on your tips, it works perfectly as expected, Close this FR now. Put this tip to README will help others someday 👍
