### ISSUE TITLE
Add show specific (or all) PageTiminings via options

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#184]
Currently only `pageTimining` marks are getting rendered (see e.g. discussion in #183).
UserTiming e.g. extracted by WPT are not currently parsed. The reason is that they can are often spammed with third-party marks.

I think we could solve this by having an `option` with an explicit array of white-listed UserTimings (and a `true` flag for all). By default UserTimings should be turned off though.
UserTiming can also have a `startTimer-*` and `endTimer-*`, so we can render a block for the duration - e.g. visible when hovering over it.

Generally it would be nice for the standard marker to fix their visibility. e.g. when clicked once it stays high-lighted, clicked again it's off again.

Some early prototype:
<img width="680" alt="screen shot 2017-03-19 at 4 09 45 pm" src="https://cloud.githubusercontent.com/assets/1680390/24078928/8f6eda1e-0cbe-11e7-9387-3061acc79a9b.png">

**Comment by micmro** [comment]
Normal:
<img width="573" alt="screen shot 2017-03-20 at 11 39 48 pm" src="https://cloud.githubusercontent.com/assets/1680390/24104832/8db05d84-0dc6-11e7-9a2f-cfc7cc73cea4.png">

Hover or click:
<img width="645" alt="screen shot 2017-03-20 at 11 39 30 pm" src="https://cloud.githubusercontent.com/assets/1680390/24104831/8dafa0ce-0dc6-11e7-892f-c83e39d62a0d.png">

**Comment by tobli** [comment]
Wow, nice addition!

**Comment by micmro** [comment]
released with `v1.1.0`
