### ISSUE TITLE
Total don't match

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#204]
I think this can have been introduced in 2.0 but I'm not 100% sure (ping @beenanner ).
If you sum all timings it should add up to the total, but now it seems it is larger. I think the problem is that the SSL time is missing from the total, can that be right?

![totaldontmatch](https://cloud.githubusercontent.com/assets/540757/26122908/5f69944c-3a79-11e7-8958-e1bf8356935a.png)

**Comment by soulgalore** [comment]
Ahh sorry the SSL time is included in the connect time to be backward compatible with the HAR spec 1.1.

**Comment by micmro** [comment]
Perhaps we can add a little note or tooltip to the `connect` time (only showing for HAR >= 1.2). If even you got confused about it non-power-user will surly find this strange.
