### ISSUE TITLE
Problem rendering HAR from WebPageTest (Linux version)

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#217]
I'm trying to debug some problems with WebPageTest and it seems that something in the HAR (I'm trying out the new LInux WebPageTest version) generates an error and don't generate the waterfall:
<img width="474" alt="screen shot 2018-02-13 at 9 21 29 am" src="https://user-images.githubusercontent.com/540757/36139848-69a9680e-109f-11e8-9eba-84806001d273.png">

And the HAR:
https://gist.github.com/soulgalore/bfe2be5916f85c2a6d4b34f3be285b92

**Comment by micmro** [comment]
Looks like we need an additional guard against `null` in `escapeHtml `: https://github.com/micmro/PerfCascade/blob/master/src/ts/helpers/parse.ts#L127.

Will check tonight

**Comment by micmro** [comment]
fixed with `v2.2.2`

**Comment by soulgalore** [comment]
thanks @micmro !
