### ISSUE TITLE
Not a numbers instead of values

### ISSUE THREAD

**Issue by suratovvlad** [micmro/PerfCascade#224]
Hi! 

I've faced with strange behaviour of waterfall on some HAR files. It shows 'Nan's instead of real values for each entry.

![screenshot from 2018-03-20 12-52-40](https://user-images.githubusercontent.com/3812290/37647568-99e7d0c8-2c3d-11e8-9471-87391553f8fb.png)
![screenshot from 2018-03-20 13-00-52](https://user-images.githubusercontent.com/3812290/37648016-d6d71a56-2c3e-11e8-84cb-9eba4ae4dd4e.png)

Could you check it?

I attach the unzipped HAR files with '.txt' exstension
[google_issue.har.txt](https://github.com/micmro/PerfCascade/files/1828762/google_issue.har.txt)
[skype_issue.har.txt](https://github.com/micmro/PerfCascade/files/1828763/skype_issue.har.txt)

I've took that HAR from Chrome from [this URL](https://www.google.ru/search?q=isfahan&newwindow=1&dcr=0&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjvu6Coz_DZAhUJAZoKHV-tAxgQ_AUICigB&biw=1280&bih=910)

Logs from console
![screenshot from 2018-03-20 12-57-11](https://user-images.githubusercontent.com/3812290/37647827-4beafe94-2c3e-11e8-9d49-19bbdf15f70c.png)
[logs.txt](https://github.com/micmro/PerfCascade/files/1828742/logs.txt)

**Comment by micmro** [comment]
Hi @suratovvlad,
the problem with both is that the `log.pages[0].startedDateTime` attribute (line 12) of the documents is an empty string. Without this timestamp it is not possible to calculate the timings as there is nothing to reference them to.
