### ISSUE TITLE
Add timing after each bar

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#23]
Add total time after the each bar. This is a super ugly example but hope it makes it more understandable. 

![timings](https://cloud.githubusercontent.com/assets/540757/13678197/c27dba94-e6ed-11e5-823a-c16fdf7e9c3f.png)

**Comment by micmro** [comment]
I see how this could be useful at times, but we should be careful not to clutter the UI. It will be fine if we pick a subtle grey or use transparency.

**Comment by soulgalore** [comment]
I'm thinking like this: How can we make it easy to spot problems as fast as possible? I like the idea that you don't need to click/hover to see important stuff but I agree it depends on how much can the UI take? hmm.

**Comment by micmro** [comment]
Added
