### ISSUE TITLE
Rendering bug in Edge

### ISSUE THREAD

**Issue by ileniazappavigna** [micmro/PerfCascade#231]
Hi,
we have detected some rendering bugs about the foreignObject position. And the position bug increases while you go down with the bottom rows.
Scrollbars are not positioned at 100% and sometimes texts are hidden and not correctly displayed. Browser used Chrome v66.
[browsertime_har.zip](https://github.com/micmro/PerfCascade/files/2017087/browsertime_har.zip)
![perfcascade-screenshot](https://user-images.githubusercontent.com/17063477/40237714-8ada874a-5ab1-11e8-95b0-fe831303415c.png)

**Comment by micmro** [comment]
Thanks for flagging this. Strange I tried to verify it with chrome 66 and could not reproduce this behaviour. Which OS do you use? Can you try to run the same in an incognito window to rule out browser plugins?

**Comment by ileniazappavigna** [comment]
thanks for your reply. i have tried with other pc and it works. probably this bug is related to some drivers installed on my machine. 
while i have noticed other bugs:
- EDGE: that the inner tabs (general, request,....) do not work
- IE11: it does not work. i can't see anything.

**Comment by micmro** [comment]
Cool, thanks, will look into these. But will have to re-setup my Windows test VM first.

**Comment by micmro** [comment]
I have fixed the broken tabs in Edge with release `v2.5.1`.
