### ISSUE TITLE
Add JSON as upload type

### ISSUE THREAD

**Issue by GeneralCarter** [micmro/PerfCascade#234]
Sorry this is part question, part feature request. please delete if this is not an appropriate issue.

I would like to be able to capture request logs from users on a website. I'm currently using [GetEntries](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntries) is their a way to programmatically get an .har file? 
The goal is to generate a chart using data logged from the browser (by users).

Does this feature make sense to add to PerfCascade or build another tool.
Actually performance-bookmarklet maybe a better starting point for me.

This is something I'm interested in working on, I'm interested in your input.
These are some really awesome tools, nice work @micmro and all contributors

**Comment by micmro** [comment]
Hi @GeneralCarter,
Sorry for the late response. Thanks I'm glad you find them useful.
I think it would be possible to generate a HAR structure based on the Timing APIs, but it would not have as much detail as say the browsers HAR export or [WebPageTest](https://www.webpagetest.org/). Also the default buffer is just 150 entries, [but you can increase it at runtime](https://developer.mozilla.org/en-US/docs/Web/API/Performance/setResourceTimingBufferSize).

performance-bookmarklet uses several Timing APIs as well to visualize them, so looking at it might help you building a similar tool.

**Comment by GeneralCarter** [comment]
If anyone is interested or has feedback, I'm starting to add support for PerformanceEntries ([getEntries](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntries)) 
Branch: https://github.com/GeneralCarter/PerfCascade/tree/Add_Performance_TimelineAPI_Support
