### ISSUE TITLE
Has a hidden dependency of zip.js

### ISSUE THREAD

**Issue by ypetya** [micmro/PerfCascade#235]
Using the common js import not works out of the box.

The following import fails, as `zip` is not provided on window scope:

```
import { fromHar } from 'perf-cascade'
```

Given this "hidden dependency" it is not trivial to embed this into a commonjs environment.

**Comment by micmro** [comment]
Released with [v2.5.4](https://github.com/micmro/PerfCascade/releases/tag/v2.5.4)
