### ISSUE TITLE
Skip vertical lines per bar

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#24]
The vertical bar that shows the timings is unnecessary? If we are able to always show the total time and then show the timing per type inside the extra info field, then the interface will be cleaner.  And it will work the same way on both mobile and desktop.

<img width="298" alt="screen shot 2016-03-10 at 18 28 52" src="https://cloud.githubusercontent.com/assets/540757/13678257/fa9334cc-e6ed-11e5-83da-021f4588feb4.png">

**Comment by micmro** [comment]
The main intention for adding them was to help finding blocking requests in waterfalls with lots of short requests. It won't work on mobile but I'm not to concerned with that since it's a pretty different use-case. 

We could perhaps add a config object to enable and disable features.

**Comment by soulgalore** [comment]
Yep, I think a config object is the way to go, we could do a lot with that. cool!

**Comment by micmro** [comment]
Blocked by #33

**Comment by micmro** [comment]
`options.showAlignmentHelpers = false`  allows to disable them.
