### ISSUE TITLE
foreignObject rendering bug

### ISSUE THREAD

**Issue by fholzer** [micmro/PerfCascade#243]
Content of div.wrapper in the foreignObject isn't rendered correctly:
![screenshot from 2019-02-18 02-41-01](https://user-images.githubusercontent.com/1814883/52923231-ff821600-3326-11e9-888b-d4f8bf6c341c.png)

Chrome 72 on Fedora 29. After some testing I found that I could only reproduce the issue (e.g. in a sitespeed docker container) when starting chrome with the `--force-device-scale-factor=2` flag.

As this seems to be a bug in Chrome I opened an issue there: http://crbug.com/933010

**Comment by micmro** [comment]
Thanks a lot for investigating @fholzer!
