### ISSUE TITLE
Chrome generates broken HAR

### ISSUE THREAD

**Issue by kabilan-ravi** [micmro/PerfCascade#244]
Hi, I am using sitespeed to collect frontend performance. Recently i updated sitespeed to 8.9.0 docker image. After upgrade waterfall reports taken from har is not displaying properly. The timelines are missing.
Please find the har and console error that i got while viewing the har.

<img width="1436" alt="Screenshot 2019-04-04 at 12 25 06 PM" src="https://user-images.githubusercontent.com/8100164/55544391-9ee94580-56e8-11e9-8f15-ae7c24008e07.png">
<img width="541" alt="Screenshot 2019-04-04 at 11 26 50 AM" src="https://user-images.githubusercontent.com/8100164/55544404-a4df2680-56e8-11e9-978b-80a1abc902ec.png">
[AllTickets-chrome-2019-04-03075521.har.gz](https://github.com/micmro/PerfCascade/files/3042675/AllTickets-chrome-2019-04-03075521.har.gz)

**Comment by kabilan-ravi** [comment]
I checked with sitespeed team, it seems to be the issue with broken har. So raising bug here

**Comment by micmro** [comment]
Cool thanks @kabilan-ravi!

**Comment by soulgalore** [comment]
Let me re-open, I think we still could handle this better right? I can have a look on Sunday. There are some timings missing but we should catch that I think.

**Comment by micmro** [comment]
I quickly looked at it and have a fix for it in https://github.com/micmro/PerfCascade/pull/245, however the visualization misses the initial time and starts from the first valid time.
<img width="1213" alt="Screen Shot 2019-04-05 at 9 21 35 AM" src="https://user-images.githubusercontent.com/1680390/55610924-47001c80-5784-11e9-9707-6f7087491d09.png">

**Comment by kabilan-ravi** [comment]
@micmro and @soulgalore Thanks for the fix.

**Comment by micmro** [comment]
released with `v2.5.7`
