### ISSUE TITLE
I need  to pass Json data instead of har file in Perf-cascade

### ISSUE THREAD

**Issue by surya0014** [micmro/PerfCascade#249]
how  to create a parser  to pass  json data instead har files to use  in fromhar() (or  new  function similar to fromhar()). 
can Perf-cascade be deploy in onpremise (without  internet )  ???

**Comment by micmro** [comment]
As mentioned in #246 you will need to convert/match your JSON data (I don't know what this looks like) to the [`WaterfallDocs`](https://github.com/micmro/PerfCascade/blob/master/src/ts/typing/waterfall.ts) interface.

Sure, if put it into a [PWA](https://developers.google.com/web/progressive-web-apps/) or an [electron](https://electronjs.org/) app you can deploy it without needing the internet.
