### ISSUE TITLE
Always show timings on vertical timings

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#25]
The viewer shows all timings that are inside the timing part inside of the HAR and that's super cool. But it's hard to see the actual number. 

We could show it direct after the metric name: onContentLoaded (2.32 s) in the vertical text? Then we will also see it easy on mobile.

**Comment by micmro** [comment]
Do you mean this? (couldn't get a better screenshot since the tooltip disappears):
<img width="214" alt="screen shot 2016-03-12 at 5 23 53 pm" src="https://cloud.githubusercontent.com/assets/1680390/13721886/44a1fd66-e877-11e5-8d9c-ae907da61286.png">

Good point - Like the idea!

**Comment by soulgalore** [comment]
Ah sorry , it wasn't clear. I mean just putting out the number after the vertical line:
![perfcascade svg based har waterfall viewer](https://cloud.githubusercontent.com/assets/540757/13722044/ceef1b64-e838-11e5-832e-25b1637c455e.png)

Or can we see that number today? I think it will not clutter the interface too much and it would be nice to see the number fast.

**Comment by micmro** [comment]
Oh quite different - good idea anyway! Shouldn't be too hard to add.

Might change the format of the tooltip anyway to make the total easier to see.
