### ISSUE TITLE
Graph is not showing for Json format

### ISSUE THREAD

**Issue by janarthan35** [micmro/PerfCascade#251]
Trying to pass json instead of har files.
I have  add a method  called "fromJson" instead of "fromHar" and  a separate parser instead of har.js .
I dont get chart properly
![image](https://user-images.githubusercontent.com/49895729/58170948-70342800-7cb2-11e9-898e-f629f2b8aa73.png)

**Comment by micmro** [comment]
It is hard to find out why it is not working without seeing the output data, but I assume it has to do with the calculation of the start and end times or some other differences in the format.
Does the output match the [`WaterfallDocs`](https://github.com/micmro/PerfCascade/blob/master/src/ts/typing/waterfall.ts) interface?

**Comment by janarthan35** [comment]
The  output ( svg element ) of  live demo  matches with my  above  output  ( I have given same data  ) .
Svg element  of  live demo and  my chart are same .
is there  is  any problem with css ?? 
 i need  to import  any additional css ?

**Comment by micmro** [comment]
Sorry, I did not meant the structure of the SVG, but the JSON object that is passed to the `PerfCascade` constructor (e.g. [here](https://github.com/micmro/PerfCascade/blob/master/src/ts/main.ts#L85)).

But right, there is also the `perf-cascade.css` CSS file.

**Comment by janarthan35** [comment]
Data is available before passing it to  PerfCascade constructor.
I have copied  css  from "perf-cascade.css "  and  pasted in my component but  still it didn't work .
The data  before passing to PerfCascade constructor :
{  
   docIsTLS:true,
   durationMs:11929,
   entries:[  
      {  
         end:2388,
         responseDetails:{  
            icon:{  
               …
            },
            indicators:Array(2),
            requestType:"html",
            rowClass:"row-item",
            statusCode:200
         }         segments:(4)         [  
            {  
               end:1652,
               start:966,
               total:686,
               type:"connect"
            },
            {  
               end:1727,
               start:1652,
               total:75,
               type:"send"
            },
            {  
               end:1953,
               start:1727,
               total:226,
               type:"wait"
            },
            {  
               end:2386,
               start:1953,
               total:433,
               type:"receive"
            }
         ],
         start:966,
         tabs:[  
            {  
               content:"<h2 class="               no-boder">Errors</h2>↵    <dl>↵      <d…r/Status Code</dt>↵      <dd>200 OK</dd>↵    <dl>",
               tabClass:"",
               title:"General"
            },
            {  
               content:"<dl>↵      ↵      <dt >Method</dt>↵      <dd>GET</…ll Request Headers</h2>↵    <dl>↵      ↵    </dl>",
               tabClass:"",
               title:"Request"
            },
            {  
               content:"<dl>↵      ↵      <dt >Status</dt>↵      <dd>200 O…l Response Headers</h2>↵    <dl>↵      ↵    </dl>",
               tabClass:"",
               title:"Response"
            },
            {  
               content:"↵      <dt class="               total">Total</dt>↵      <dd>1422…"receive">Receive</dt>↵      <dd>433 ms</dd>↵    ",
               tabClass:"",
               title:"Timings"
            },
            {  
               renderContent:ƒ,
               tabClass:"raw-data",
               title:"Raw Data"
            }
         ],
         total:1422,
         url:"https://www.google.com/"
      }
   ],
   marks:[  

   ],
   title:"googleHomePage"
}

**Comment by janarthan35** [comment]
Thanks  for  your  support. I got  waterfall chart  by passing  json data.
