### ISSUE TITLE
Example uses deprecated 'leftColumnWith'

### ISSUE THREAD

**Issue by sciatro** [micmro/PerfCascade#258]
[The example site](https://micmro.github.io/PerfCascade/) still uses `leftColumnWith`, the typo that was fixed in #207 and is [now deprecated](https://github.com/micmro/PerfCascade/blob/23ca585c103e5fec623c589bf64430bb8091f4a7/src/ts/main.ts#L40]). 

From the console after loading the demo page:

    Depreciation Warning: The option 'leftColumnWith' has been fixed to 'leftColumnWidth', please update your code as this will get deprecated in the future

Great project.

**Comment by micmro** [comment]
Thanks a lot - fixed now.
