### ISSUE TITLE
Design changes?

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#26]
Got a couple of suggestions. Only suggestions :) Would be cool if we can make some of them configurable.
- The background for the waterfall graph should be white and 1-2 px gap between the bars (today they are line in line right). Think that will make the look and feel even nicer.
- The extra info layer could also be white.
- Each bar will have different colors depending on the content type. We discussed this before in another issue.  I really like that because it makes it so easy to see what kind of content the page uses.
- Redirects, errors can have different background colors per row. Think we also discuss that, but could be that it is hard to implement?
- Skip the icons. Yep it was my idea but it was probably a bad idea. Thinking we could use that space to show a small version of the image if the response is an image as Firefox do.

**Comment by micmro** [comment]
> The background for the waterfall graph should be white and 1-2 px gap between the bars (today they are line in line right). Think that will make the look and feel even nicer.
> The extra info layer could also be white.

Most of the colours are in the CSS and the bar-heigh can also be passed into the chart constructor (currently it's 23px `createWaterfallSvg(data, 23)`). Can you play around with it a bit and see if that's flexible enough for you?

> Each bar will have different colors depending on the content type. We discussed this before in another issue. I really like that because it makes it so easy to see what kind of content the page uses.

Do you mean the background of each row or the request bar? I personally like to break it into it's components - can you create a mockup of what you mean? 

> Redirects, errors can have different background colors per row. Think we also discuss that, but could be that it is hard to implement?

Had that in the back of my head as well - should be simple enough, just need to find the time to do it. Opened #27 for this.

> Skip the icons. Yep it was my idea but it was probably a bad idea. Thinking we could use that space to show a small version of the image if the response is an image as Firefox do.

Need to think about this a bit, perhaps we can add a config-flag for this. Small images would only make sense if we have a server side resizer - it would be horrible to download giant images for the tiny preview.

**Comment by soulgalore** [comment]
> Most of the colours are in the CSS and the bar-heigh can also be passed into the chart constructor (currently it's 23px createWaterfallSvg(data, 23)). Can you play around with it a bit and see if that's flexible enough for you?

Cool will test it out.

> Do you mean the background of each row or the request bar? I personally like to break it into it's components - can you create a mockup of what you mean?

Yes :)

**Comment by micmro** [comment]
Close this for now, please create new issues if anything was missing.
