### ISSUE TITLE
Copy response content to clipboard?

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#261]
Hi @micmro the functionality to get the HTML or response of a requests has been great for me, I've used in many times to compare content before/after a regression. Copy/pasting it into Visual Code and then using the compare feature its great.

One thing I'm wondering is the best way to make it easier to copy the content. Right now I scroll the content and it takes some time on large Wikipedia pages. Wondering if we should use the clipboard API for copy (for the browsers that supports) or is it a better way? Would love to be able to copy the response content and paste into code :)

Best
Peter

**Comment by micmro** [comment]
Hi @soulgalore, I manage to implement it this weekend. Please have a look at the PR and play around with it a bit and let me know what you think.

**Comment by soulgalore** [comment]
Great @micmro I actually started this last week but my skills aren't as good as yours so I didn't finish. It works great but made a small comment on the PR about moving to just copy content  (the next tab), that's the data we use when we compare what kind content we had before/after a regression.

**Comment by micmro** [comment]
Released with `2.7.0`
