### ISSUE TITLE
white area blocks some fields

### ISSUE THREAD

**Issue by matti** [micmro/PerfCascade#264]
<img width="1915" alt="results" src="https://user-images.githubusercontent.com/3893/68994261-ac26ff00-0889-11ea-99a5-5cdf6f8a6e7d.png">

the full source at: https://gist.github.com/matti/5984a7bd3c64c1e2b07bcf9b5f76175e

**Comment by matti** [comment]
setting `width: 99%` (or any width) "fixes" this (I set it to my `div#output`)

**Comment by micmro** [comment]
Based on the font rendering in the screenshot it looks like you might not apply [`perf-cascade.css`](https://github.com/micmro/PerfCascade/blob/release/perf-cascade.css)? Could you double-check if it gets loaded?

**Comment by matti** [comment]
source at https://gist.github.com/matti/5984a7bd3c64c1e2b07bcf9b5f76175e#file-perfcascade-html-L7

I also noticed that font rendering looks weird, but all other styles apply correctly. 99% was not enough, currrently set to:
```
      div#output {
        width: 97%;
      }
```

and now everything renders correctly, although font is still times new romanish

**Comment by matti** [comment]
so I'm doing it like this (I have my weird reasons for this):
```
    <style>
      <%= File.read "node_modules/perf-cascade/dist/perf-cascade.css" %>
    </style>
```
