### ISSUE TITLE
start of the waterfall is "missing" a block

### ISSUE THREAD

**Issue by matti** [micmro/PerfCascade#265]
<img width="1138" alt="results" src="https://user-images.githubusercontent.com/3893/69011114-8ecc6080-096f-11ea-9136-8581a27886f7.png">

**Comment by matti** [comment]
<img width="644" alt="results" src="https://user-images.githubusercontent.com/3893/69011218-f040ff00-0970-11ea-8587-867a8c8668aa.png">

**Comment by micmro** [comment]
Could you check if it works on the demo page (https://micmro.github.io/PerfCascade/)?

I am suspecting that both this and #264 have to do with some issues in the CSS setup.
