### ISSUE TITLE
Responses with HTTP status code of 0 not highlighted

### ISSUE THREAD

**Issue by JonathanWylie** [micmro/PerfCascade#267]
When displaying a HAR when a component did not get a response, eg connection refused, or connection timeout etc then the http status code defaults to 0.
I would like perf cascade to highlight them when displaying the har, so it is clear there was a problem. Then I will put the reason, eg connection timeout, in the "comment", so the user can easily there was a problem with the component and what the cause was.
Or perhaps use the indicators for this, so indicate it with the error icon, if it has a status code of 0, and if it has a comment, include that in the error message.

I am willing to make a pull request if this behaviour is wanted.

**Comment by micmro** [comment]
@JonathanWylie I've setup a PR (#277) to address this (screenshot below), but used a manually changed HAR file, do you have any real-world examples? I assume the "comment" you mentioned would be in the the `statusText` field?

<img width="656" alt="Screen Shot 2021-04-18 at 1 48 14 PM" src="https://user-images.githubusercontent.com/1680390/115155269-221a3180-a04d-11eb-911f-a8e7b9b95f97.png">

**Comment by micmro** [comment]
Released with [`2.9.0`](https://github.com/micmro/PerfCascade/releases/tag/v2.9.0)
