### ISSUE TITLE
Redirect and error row BG colour

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#27]
Redirects (3xx), errors (client 4xx, server 5xx?) to have different row background colours.

See WPT as reference.
<img width="952" alt="screen shot 2016-03-12 at 5 45 16 pm" src="https://cloud.githubusercontent.com/assets/1680390/13721999/6fc0d65e-e87a-11e5-9178-cbb39ad11a4a.png">

3xx: #ffff60
4xx: #ff6060

**Comment by soulgalore** [comment]
Think we could use the red also for 5xx or what do you think? All these are evil, as long as we skip 304 :)

**Comment by micmro** [comment]
Youp - perhaps a slightly different shade, just copy and pasted the WPT ones - I suppose we'll adjust them anyway.
