### ISSUE TITLE
Last release broken for some HARs

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#276]
Its seems the last release throw errors for some URLS:
<img width="600" alt="Screenshot 2021-03-30 at 13 57 05" src="https://user-images.githubusercontent.com/540757/112984985-e122b180-915f-11eb-94bb-2df45ce76405.png">

How to reproduce:
1. Go to https://micmro.github.io/PerfCascade/
2.  Click "Use example HAR"

I can have a look later this week if you don't have time @micmro !

**Comment by hemm0** [comment]
Bump!

**Comment by soulgalore** [comment]
I rollbacked in sitespeed.io projects since I have a limited time, but I can help test if someone has time to do a PR.

**Comment by micmro** [comment]
Will check, might be caused by some dependency updates.

**Comment by micmro** [comment]
This should be fixed with `2.8.1`

https://github.com/micmro/PerfCascade/compare/v2.8.0-source...v2.8.1-source
