### ISSUE TITLE
x-axis value disappearing in waterfall model representation of page load

### ISSUE THREAD

**Issue by manjunathpremkumar** [micmro/PerfCascade#288]
Hi,

We noticed that in our one of scripted journey test, x-axis values (in seconds) are not appearing for waterfall model representation of page load. We are able to reproduce this issue multiple times. Attached the HAR file for the page loaded and screenshot of the issue.

[IBE_Guest_PassengerDetails_Page_Load-chrome-2022-09-07183603.har.gz](https://github.com/micmro/PerfCascade/files/9604749/IBE_Guest_PassengerDetails_Page_Load-chrome-2022-09-07183603.har.gz)
![X-axis](https://user-images.githubusercontent.com/43643055/191185129-6e8505a4-7bba-44d3-bcd9-5b24fae6e2c5.JPG)
Note: This is happening for this particular user journey and not for other journeys.

**Comment by manjunathpremkumar** [comment]
@soulgalore - by any chance you got time to see this issue, I know you will be super occupied :)

**Comment by micmro** [comment]
Looks like this has to do with floating point precision in this function:
https://github.com/micmro/PerfCascade/blob/main/src/ts/waterfall/sub-components/svg-general-components.ts#L71-L85

Will dig into this more durning the weekend.

**Comment by micmro** [comment]
Fixed with `3.0.3`

**Comment by micmro** [comment]
<img width="1759" alt="Screen Shot 2022-11-12 at 9 39 17 PM" src="https://user-images.githubusercontent.com/1680390/201502958-439b4225-e92a-41c7-9464-93e218404529.png">

**Comment by manjunathpremkumar** [comment]
Thanks a lot!
