### ISSUE TITLE
Colour Setup

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#4]
- Same as WPT
- Switch or split view for timing and content type?

**Comment by micmro** [comment]
### WPT Colours

#1f7c83 - DNS Lookup
#e58226 - Initial Connection
#c141cd - SSL Negotiation
#1fe11f - Time to First Byte
#1977dd - Content Download

**Full row background colours:**
#ffff60 - 3xx response
#ff6060 -  4xx+ response 

**Event colours:**
#28bc00 - Start Render
#8fbc83 - msFirstPaint
#d888df - DOM Content Loaded
#c0c0ff - On Load
#0000ff - Document Complete
#69009E - User Timings (not sure if needed)

<img width="764" alt="screen shot 2015-12-20 at 9 41 48 pm" src="https://cloud.githubusercontent.com/assets/1680390/11918079/af570de8-a765-11e5-8dbf-9fc131f8fedd.png">

<img width="940" alt="screen shot 2015-12-20 at 10 04 21 pm" src="https://cloud.githubusercontent.com/assets/1680390/11918082/b6b165d4-a765-11e5-80b1-b870bcd5b558.png">

**Comment by micmro** [comment]
### Missing/Mismatching Timings
- `blocked` is not visualized in WPT
- it seems like both `send` and `wait` could map to TTFB

**Comment by soulgalore** [comment]
There is also the color by content type in WPT (you see that always when you compare runs):
<img width="931" alt="screen shot 2016-01-22 at 13 27 24" src="https://cloud.githubusercontent.com/assets/540757/12510690/083bdc62-c10c-11e5-9f46-1d591c8eb96c.png">

I think it's important to make it super easy to see the content type of the response, but not sure if it's best done by coloring or having different images per type? What do you think?

**Comment by micmro** [comment]
I currently have a bar below the segments to indicate the type but it's not super obvious - I like the idea of an additional icon. We just need to source some decent ones, do you have suggestions?
<img width="194" alt="screen shot 2016-01-23 at 7 40 09 pm" src="https://cloud.githubusercontent.com/assets/1680390/12529803/29ddab04-c209-11e5-8715-0a4838b80840.png">

**Comment by soulgalore** [comment]
ah sorry I didn't understand the line under the bar, but know when I know it's pretty cool :) I'll get back tonight. Maybe what's missing is a explanation of the colors at the bottom of the waterfall.

**Comment by soulgalore** [comment]
I like the symbols that Pingdom uses (http://tools.pingdom.com/fpt/#!/dHia7l/http://www.auxoisnature.com/preparer-un-trek-photo/) I can have a look to see if I can find an Open Source alternative.

**Comment by micmro** [comment]
They look quite nice - I tried to use them as inspiration and come up with some we can use. What do you think? Are they clear enough? Any other ones I missed?
![type icons](https://cloud.githubusercontent.com/assets/1680390/12938213/f43e9a3c-cff3-11e5-8e9d-4df72edd9a6a.png)

MIME Types
- JS
- HTML
- Image
- CSS
- Font
- SVG
- Plain/Text
- Other

Indicators
- Redirect
- Warning
- TLS/SSL

**Comment by soulgalore** [comment]
I've been looking also haven't found any, I think these look good. Maybe we should have one for 40X/50X? WPT highlights the whole row in that case but maybe a symbol is enough.

Do we have space to have multiple symbols on one row? I'm thinking if the site use HTTPS then (hopefully hehe) every asset will have the lock symbol, one MIME type and maybe a warning?

**Comment by micmro** [comment]
Good idea - I'll play around with marking the row and an icon and see what works better. Yes, we have, respectively make more space - I was thinking we can dynamically add as much space as needed.

Perhaps we can have the inverse for HTTPS sites - a warning if an asset is not HTTPS - e.g. if the main document request is HTTPS.

**Comment by micmro** [comment]
Colours are defined now will track other work via #6
