### ISSUE TITLE
Compact display of the URL

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#5]
I can make a generic function to make a name of the URL smaller. Things you want to know/see:
- HTTP/HTTPS
- domain
- the last part of the URL but make difference between base page and request parameters
- content type (depending on how what kind of view we use)

**Comment by micmro** [comment]
After cropping the domain we could show additional infos on tap/hover, e.g. the exact timing, similar to WPT.

On hover:
<img width="453" alt="screen shot 2015-12-21 at 9 11 44 pm" src="https://cloud.githubusercontent.com/assets/1680390/11930540/adf1f0cc-a827-11e5-8a2b-934e4bf22385.png">

On click:
<img width="957" alt="screen shot 2015-12-21 at 9 11 27 pm" src="https://cloud.githubusercontent.com/assets/1680390/11930530/99067782-a827-11e5-8248-764a7c1d06d2.png">

Other interesting infos (a lot of those could be highlight-flags):
- `httpVersion`
- `headersSize`
- Encoding
- `bodySize`
- `_transferSize` (perhaps as with ratio to `bodySize` + `headersSize`)
- Perhaps we can calculate to request (`Cookie`) and response (`Set-Cookie`) cookie size
- cache settings (request and response)
- Font type used (e.g. suggest woff2)

**Comment by micmro** [comment]
I've setup a branch that moves the URL to the right and crops it similar to WPT:
- full url if short enough
- else remove query string
- if still too long show only authority and last path segment)

Additionally when you hover over the urls on the left it extends to the full name as well (see screenshot):
<img width="775" alt="screen shot 2016-01-10 at 11 31 25 pm" src="https://cloud.githubusercontent.com/assets/1680390/12222033/e034025c-b7f2-11e5-91d9-d8e67f3bdea4.png">

I think this could work quite well and looks a bit cleaner. The only disadvantage is that it takes a bit more space.

**Comment by micmro** [comment]
Hi Peter, you had claimed this task - sorry, just noticed this now ^^. I've updated the text shortening as part of moving the text over but there might be room for additional tweaking.

Otherwise if you're happy enough we could close this task.

**Comment by soulgalore** [comment]
Hey @micmro np, I've should have added a comment also it the issue that I've planned to work on it :) 

Cool, will have a look this weekend.

**Comment by micmro** [comment]
Hi @soulgalore, can we close this issue or do you plan to enhance this more?

**Comment by soulgalore** [comment]
let me look at it tonight and get back!

**Comment by soulgalore** [comment]
I'll send a PR tonight thinking it would be nice to pickup the end of the filename, that usually tells us which file it is.
