### ISSUE TITLE
Change sec to s?

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#51]
If there's a site that is slow, it is crowded in the end of the graph. What do you think about changing from sec to s?

<img width="975" alt="screen shot 2016-08-19 at 21 39 53" src="https://cloud.githubusercontent.com/assets/540757/17822138/97cde336-6655-11e6-8be8-1ba2cf3cdc3d.png">

**Comment by micmro** [comment]
Sounds good. Like the idea!

**Comment by soulgalore** [comment]
Great, I got some more reports of HAR files that fails, will try to fix it tonight.
