### ISSUE TITLE
Need legends for waterfall colors

### ISSUE THREAD

**Issue by softwareklinic** [micmro/PerfCascade#54]
Something like what web page test or HTTP Watch does

![har](https://cloud.githubusercontent.com/assets/7537289/18538975/fb915208-7ad8-11e6-9aac-f95bc53b71a2.png)

**Comment by micmro** [comment]
Should be easily addable as an option.

I'm just back from vacation and have some catching up to do so it might take a few weeks to get this added. Alternatively PRs are always welcome.

**Comment by micmro** [comment]
<img width="641" alt="screen shot 2016-12-04 at 3 43 38 pm" src="https://cloud.githubusercontent.com/assets/1680390/20864552/5c09771a-ba39-11e6-90fe-f3887ddc463b.png">

**Comment by micmro** [comment]
Added with v0.2.8.
Please feel free to create another issue if there are any metrics are missing.
