### ISSUE TITLE
Bundled js gone from npm

### ISSUE THREAD

**Issue by hmil** [micmro/PerfCascade#57]
Hi there,

It seems like the built js has disappeared from the npm package between versions 0.2.1 and 0.2.3. Any chance of getting it back?

Thanks

**Comment by micmro** [comment]
Sorry for that. I had removed it on purpose, assuming there was no value in
adding it.
Sure, I can add it back (possibly not before saturday though).

Just out of curiosity how are you using the build file?

Michael

**Comment by hmil** [comment]
Oh yeah I see.

So I'm using npm as my front-end package manager as well as the package manager for build tools and stuff. This way I don't have to deal with an over the top setup involving multiple package managers (talking about you bower).
I'm then specifying all the css and js I need in a JSON file. A gulp task then pulls those files from `node_modules` into my `dist` folder and writes the proper `<link />` and `<script />` tags to my index.html.
I really like the simplicity of this setup and I can only assume other people are doing the same thing.

Anyway, back to the topic. Since this is a front-end library it just seems natural that it should ship as a bundle. Whether or not to include the original source files is up to you though I would argue it is redundant once you are shipping the bundle. Plus you are shipping the typings as well so that and the bundle should cover most use-cases.

**Comment by micmro** [comment]
Sorry, actually I misread your request and thought you meant the bundling script (`Gruntfile.js`) :).
This makes perfect sense - I've added it back now (via the `./dist` directory).

**Comment by micmro** [comment]
Let me know if this works for you now, or if you have any other suggestions.

This is my first front-end npm package (actually backend as well, but that's easier to reason about) so all feedback is welcome.
