### ISSUE TITLE
Add highlight rules for suspicious requests

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#6]
> One thing I like with the current modified version we use is that we have the ability to run some super simple rules on an asset, so that we can highlight if something is wrong (like missing cache headers). It looks like this:
> <img width="429" alt="eba21276-a246-11e5-93c0-b1ccd335374b" src="https://cloud.githubusercontent.com/assets/1680390/11917760/9947c90a-a758-11e5-98c6-0f8aaae73945.png">

**Comment by micmro** [comment]
I've spend some time getting a fixed width bar before the flexible waterfall diagram and finally got it working, but than had to realize it won't work in IE/Edge once I tried it in my VM :( :
See example in Gist: https://gist.github.com/micmro/2d3da8e6d4ac13687dca 

I think it'd be better to work across browsers, so alternatively we could make it JS based (with a throttled resize event handler) or have that part flexible as well.

@andydavies @soulgalore  Do you guys have any ideas how to get this working via SVG/CSS that would work across browsers - or alternative layouts?

I was thinking of something like this (icons are just an example):
![sidebar-idea](https://cloud.githubusercontent.com/assets/1680390/12078468/1d50dd6e-b257-11e5-8994-19930c6b93a2.png)

**Comment by micmro** [comment]
I think I might have a solution for Edge: https://jsfiddle.net/a12x9c56/10/, using html in the `foreignObject` for the legend in the bar on the left.

**Comment by soulgalore** [comment]
@micmro havent had time to look at anything yet, trying to finish off another project, will start in a couple of days. looks really cool what you've done so far :)

**Comment by micmro** [comment]
Happy new year!
Thanks. NP at all. 

BTW I found a simpler solution for the SVG issue (with nester svg-tags and padding) and set up a branch for this issue: `request-hightlight-#6`

**Comment by micmro** [comment]
Added secure connections as an example icon. It needs a bit cleanup but it's now mainly about deciding what issues to highlight :).

<img width="783" alt="screen shot 2016-01-06 at 11 52 32 pm" src="https://cloud.githubusercontent.com/assets/1680390/12145271/a1459878-b4d0-11e5-9670-4be397ce3fed.png">

**Comment by soulgalore** [comment]
Yes looks cool. What's your feeling about the name, should it always be to the left or as it is today?

About the highlighting: Think it depends on what else we want to show and how. How much space will we have? :)

**Comment by micmro** [comment]
The reason I had aligned it like this for the perf-bookmarklet was to leave as much space for the text as possible without having a dedicated text column. Though now that I've setup the boilerplate to actually have a fixed width column we could theoretically move it, since I need to admit that it adds a bit visual clutter.

I'd suggest we can dynamically calculate the amount of space we need, depending on the number of flag we need to show.

**Comment by micmro** [comment]
<img width="127" alt="screen shot 2016-02-14 at 9 42 22 pm" src="https://cloud.githubusercontent.com/assets/1680390/13033698/dfd9a244-d363-11e5-9297-8dbfd67fe06c.png">
Added icons for all response types (via #4) and highlighting of the following issues:
- no-cache
- no TLS
- no gzip
- 3xx
- 4xx
- 5xx
- no MIME returned (seen it on one test site, so I added it)

@soulgalore @andydavies Any feedback or ideas for other highlights else I'd close this issue?

**Comment by soulgalore** [comment]
This is cool! We can do one thing for the no-cache, if the response is 204 we just skip it (if it's tracking response). I need to go through some more HARs just to check, maybe there are some more things we can use for warnings.

**Comment by micmro** [comment]
Close this issue, will create new issues for other ideas.
