### ISSUE TITLE
More vertical lines to make it easier to find start/end 

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#62]
Today we have vertical lines every second. If the whole waterfall is only a couple seconds, we have space to add small vertical lines say every 200 ms, that would make it easier to spot when requests start/ends. I'm not sure how to add it and how to make the logic that only add it when the width is larger than X. It would be nice if the color is vaguer than the 1 second lines and we don't need to have any numbers below, only the lines that help guide us through.

**Comment by micmro** [comment]
Good idea, will add it.

**Comment by micmro** [comment]
added via v0.2.7
<img width="285" alt="screen shot 2016-12-04 at 11 38 26 am" src="https://cloud.githubusercontent.com/assets/1680390/20863686/327ac26e-ba16-11e6-9ff2-e94a2332ddfa.png">

**Comment by soulgalore** [comment]
wow looks great! :)

**Comment by soulgalore** [comment]
I talked with @tobli and he has some problems in his Retina display to actually see the lines:

![image](https://cloud.githubusercontent.com/assets/540757/20891895/20c90a2a-bada-11e6-9940-c3327211f094.png)

"The sub-second line were to thin at 0.25 points. Most disappeared on my retina screen"

**Comment by micmro** [comment]
Strange, i use a retina MBP and they looked fine, can he try which width
works wellnon his machine and i'll adapt then accordingly?

**Comment by tobli** [comment]
.5 looks good. Chrome and Firefox renders .25 ok, but Safari does not.
