### ISSUE TITLE
Update icons?

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#63]
I don't if you have tested @micmro but we have integrated PerfCascade in sitespeed.io and with small fixes going it next release, it will look great. I've added some PRs that will make it easier to "read" the graph, hope you like them. 

One thing, we turn off the icons, to much clutter (I know it was my idea from the beginning sorry). I think what could be one solution is to just have icons for content type, then each row will have one icon. I'm also in favor changing the icons (I can do that if you agree and help out a little). I think we can find some with a license that we feel are ok, I kind like those here: http://www.flaticon.com/search?word=content%20type

**Comment by micmro** [comment]
I had just quickly thrown them together myself and I'm not quite a designer, so I don't feel attachment to them :). Would be great if you can source some that work with the repos MIT license.
Just let me know if you need my help with anything.

**Comment by soulgalore** [comment]
Cool, I'll do that when I get back home in a week or so. Would love a release before that though with the changes we have + possible more horizontal lines, if you have time :)

**Comment by soulgalore** [comment]
@beenanner @tobli have you seen any good svg icons we could use?

**Comment by beenanner** [comment]
I did a quick search on http://www.iconninja.com/, but didn't find any as clean as what you found @soulgalore.

**Comment by soulgalore** [comment]
Maybe we can use Font Awesome and then when 5.0 upgrade to the latest? https://github.com/encharm/Font-Awesome-SVG-PNG/tree/master/black/svg Haven't mapped everything yet though.

**Comment by soulgalore** [comment]
@micmro I need your help on this, I got totally stuck on my lack of SVG skills. I've tried adding some of the svgs in https://github.com/encharm/Font-Awesome-SVG-PNG/tree/master/black/svg but however I do they are just tooo big?

**Comment by micmro** [comment]
Cool. Np, will have a look.
Might have to wait for the weekend though, have my Korean course tomorrow
night.

**Comment by tobli** [comment]
I have a PR coming up for enabling mime icons and indicator icons separately. Just needs some cleanup to submit.

**Comment by micmro** [comment]
Hi @soulgalore, where do you try to add them? To `src/ts/helpers/icons.ts`? 

Looking at [one](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/align-center.svg?short_path=15bfe9a) it looks like you have to remove or change the width, height and viewbox in the `<svg width="1792" height="1792" viewBox="0 0 1792 1792" viewBox="0 0 1792 1792` part .

If you let me know which ones you want to use where I could also add them for you.

**Comment by soulgalore** [comment]
Hey @micmro yes, that's how I tried but somehow the path element has the size inside? Like if I take the path element only of one of the icons and then change one icon in icons.ts it just get too big and with wrong offset?

**Comment by micmro** [comment]
Sorry, looks like I was wrong, you need to maintain the `viewBox`, you could do it like this:
```
  const parser = new DOMParser()
  let test = `<svg x="${x}" y="${y}" width="18" height="18" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
      <g class="icon icon-no-tls" transform="scale(${scale})">
        <!-- start custom -->
        <path d="M1792 1344v128q0 26-19 45t-45 19h-1664q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h1664q26 0 45 19t19 45zm-384-384v128q0 26-19 45t-45 19h-896q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h896q26 0 45 19t19 45zm256-384v128q0 26-19 45t-45 19h-1408q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h1408q26 0 45 19t19 45zm-384-384v128q0 26-19 45t-45 19h-640q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h640q26 0 45 19t19 45z"/>
        <!-- end custom -->
      </g>
    </svg>`

  const doc = parser.parseFromString(test, "image/svg+xml")
  return doc.firstChild as SVGElement
```
but thats not super clean, I think using [Inkscape](https://inkscape.org/en/download/) (free OSS) or Illustrator to resize it to the baseline size of 18px by 18px (same as other icons) first would be better, than you can use the same pattern as the other icons. 

Just found a guide for Inkscape resizing [here](http://www.smileywar.com/how-to-convert-resize-images-to-svg-and-using-inline-html-using-free-tools/).

**Comment by soulgalore** [comment]
cool, thanks! I'll test it tonight! think @tobli has an PR coming to restructure the icons.
