### ISSUE TITLE
Improve request detail box

### ISSUE THREAD

**Issue by micmro** [micmro/PerfCascade#8]
Improve the detail box that is shown on `click`. Perhaps similar to WPT.

From #5 

> <img width="957" alt="screen shot 2015-12-21 at 9 11 27 pm" src="https://cloud.githubusercontent.com/assets/1680390/11930530/99067782-a827-11e5-8248-764a7c1d06d2.png">
> 
> Other interesting infos (a lot of those could be highlight-flags):
> - `httpVersion`
> - `headersSize`
> - Encoding
> - `bodySize`
> - `_transferSize` (perhaps as with ratio to `bodySize` + `headersSize`)
> - Perhaps we can calculate to request (`Cookie`) and response (`Set-Cookie`) cookie size
> - cache settings (request and response)
> - Font type used (e.g. suggest woff2)

**Comment by soulgalore** [comment]
One thing that's nice is showing the actual image (if there's one). But it needs to be lazy loaded, so that it only downloads when you click on the detailed box for that image response.

One thing that I like with Firefox built in network tab is that they show a small scaled version of the image:
<img width="771" alt="screen shot 2016-01-26 at 23 37 45" src="https://cloud.githubusercontent.com/assets/540757/12597565/f374b650-c485-11e5-8af8-aaf5dd0d60f8.png">

I like that it's so easy to identify them.

**Comment by soulgalore** [comment]
Been testing this out now when I compare HAR files in Browsertime (we will soon release 1.0). One thing that struck me is that it hard to go back and forth looking at that extra info. Would be cool to also be able to see the info for two different requests at the same time. 

I'm kind of like how Pingdom [solved it](http://tools.pingdom.com/fpt/#!/d4Ssha/http://happywheels.co.in/) by making it possible to open up multiple requests at the same time. And I also like that they use the full width displaying the extra info, you can fit in more data there.

What do think @micmro ? Try out a couple of different HARs and open/close the extra info and see how you feel.

**Comment by micmro** [comment]
I like it visually and can see how it's more convenient UX wise. It way easier in HTML, than SVG but I'll dig into it later. I'm a bit busy with work and non-tech live in the moment so it might take a bit.

**Comment by soulgalore** [comment]
No worries. I'll create a couple of issues toady, been discussing with @tobli of some changes. I'll start to implement them later (the one I can) so if you have time to just read the through it would be great, just so I know if you like them or not :)

About the extra info: One first step would be to make the extra info layer the same width as the graph, then we have more space and I think it would look better.

**Comment by micmro** [comment]
Cool, will look through them. 
Just to avoid duplicating work - I had worked a bit on the full width accordion-style info panel. But it's not fully done yet (`8-details-accordion` branch).

**Comment by soulgalore** [comment]
ok cool, that sounds great, I think (if it works) will be the best solution.
