### ISSUE TITLE
Only make 301, 302 , 303 and 307 rows yellow not 304

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#83]
We signal a redirect as a yellow row in the waterfall, but we shouldn't do that for 304 since it something good (Not Modified).

**Comment by soulgalore** [comment]
Hmm checked the code and we have an exception for 304 let me check if this is really an issue.

**Comment by tobli** [comment]
I think we can tweak the fox from d46c955cf308c7f8c9ec4ca9cdba82553756c66f a bit. It assumes all responses with a redirectURL is a 3xx, but that's not the case. I've seen 201 (created) responses on pages, and they use the Location header as well. The redirect icon might be a bit misleading in that case.

**Comment by tobli** [comment]
Let's close this until we find concrete examples of things being wrong.
