### ISSUE TITLE
Make the width of the waterfall wider if we have page timings that happens after the last request

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#84]
Today we set the width of the waterfall to the last requests but I've seen cases (especially in FF) where onload and lastVisualChange happens after that, so those metric lines aren't included in the graph. We should check the metrics we have and if they are larger than the last response time we should have that as the width (+ 500ms or something). I'll add a gist to a example HAR later.

**Comment by tobli** [comment]
Fixed in bda6e7d801bc0bb444d79cd19259f7e8fdcc78bf
