### ISSUE TITLE
Restructure the order of icons

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#86]
I think (but this is only a suggestion) that the content type icon should be to most right just before the number. And if we have errors/redirect that icon should be displayed there too.

And then the no-gzip, no-cache (and in the future more) could be displayed to the left BUT only one. It would be like a category that you should check that PerfCascade has discovered something that probably isn't perfect.

We can also in that last column only check for content that is served without TLS if the main document has TLS and then signal that with a red open lock.

**Comment by tobli** [comment]
see #100 for PR that mostly addresses the last point.

**Comment by tobli** [comment]
#121 relates to this.

**Comment by micmro** [comment]
@tobli @soulgalore  is this fixed now or is there still work remaining?

**Comment by soulgalore** [comment]
The problem for me is #129 that makes it hard for us to enable the column for icons (except content type=) since the width will vary and the name of the request sometimes fit and sometimes not. Right now we display all warnings, one fix could be to only show the most important one?

**Comment by tobli** [comment]
@soulgalore could we close this and only keep #129 open?

**Comment by soulgalore** [comment]
yep lets do that.
