### ISSUE TITLE
Change the example HAR to non hacked version

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#87]
I think the current Github example version has been hacked so for example timings aren't correct that me and @tobli thinking something was wrong in PerfCascade. It's better to try to fins a site that will display most of our use cases.

**Comment by micmro** [comment]
@soulgalore do you have any good example HAR for this?

**Comment by soulgalore** [comment]
maybe a HAR from a newspaper site (with not too many request hehe)?

**Comment by micmro** [comment]
It might be hard to find that - they usually have loads of requests :):

- http://enorm-magazin.de/ 66 requests
- https://koreaexpose.com/ 101 requests
- http://english.hani.co.kr/ 116 requests
- http://www.tagesschau.de/ 117 requests

all others The Guardian, Globe and mail, The Age, BBC, etc have more than 150

**Comment by soulgalore** [comment]
maybe it doesn't matter as long as it is an un-hacked version, the thing with the current one is that the data was manually changed to show different use cases but the data is not in sync, so it is hard to say if the error is in the HAR or in the example file.

**Comment by micmro** [comment]
updated the examples on the demo and dev page.
