### ISSUE TITLE
Open/close on the same row

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#88]
Today you open the extra info when you click on the row and the close it on the little x to the right.  I think it would be a nice user experience if also could close if you clicked on the row and the info box is open.

<img width="966" alt="screen shot 2016-12-20 at 14 23 39" src="https://cloud.githubusercontent.com/assets/540757/21352048/1a12ab2c-c6c0-11e6-9abc-2897399f7564.png">

**Comment by micmro** [comment]
That should be pretty straight-forward. I'll be traveling for a few days but could look at it when I'm back.
Just a heads up - I think I won't have a lot of internet connectivity, so probably I can't check PRs till mid of next week.

**Comment by soulgalore** [comment]
Cool. I think PRs will slow down now during the holidays too. I got some small things lined up but I nothing important :)

**Comment by tobli** [comment]
@micmro fixed this via #140 🎂
