### ISSUE TITLE
Multiple Cascade on the same page

### ISSUE THREAD

**Issue by ethyde** [micmro/PerfCascade#95]
I try to display several Cascade on the same page, they are displayed well but the opening of info window spreads to all the Cascades of the page.

**Comment by micmro** [comment]
It's cause by the way I had setup the pub-sub module, will need to refactor it to not be a singleton but an instance per waterfall (or have scope checks in the callbacks).

**Comment by micmro** [comment]
13d113a will fix this issue, but there is one more related issues with the paging in multi-run HARs. Will create another PR for that next week.

**Comment by micmro** [comment]
Hi @ethyde - this is fixed with `v0.2.18`.

**Comment by ethyde** [comment]
It's work like a charm, thx a lot ! :)
