### ISSUE TITLE
Remove generated files from git.

### ISSUE THREAD

**Issue by tobli** [micmro/PerfCascade#99]
It'd be good to not have generated files in the git repository (see discussion in https://github.com/micmro/PerfCascade/pull/78). This issue is to work out a solution that covers all use cases. The ones that come to mind are:

- [x] making a release to npm
- [x] making a GH release
- [x] making the generated js/css files available for download (not via npm)
- [x] updating the [site](https://micmro.github.io/PerfCascade/) with assets from the latest release
- [x] _something else ???_

ping @micmro 

I pushed a branch with some preliminary work.

**Comment by micmro** [comment]
Thanks @tobli, I think that sums it up quite nicely, I can't think of anything else in the movement. Perhaps you can keep in mind the use-case of releasing it to Bower (#53), but if it's to cumbersome we can just drop it, as bower seems increasingly to be on the way out (IMHO).

**Comment by micmro** [comment]
I'll start looking into this.

**Comment by tobli** [comment]
Thanks! It would make jumping between branches when running watch so much simpler.

**Comment by micmro** [comment]
Some options/inspirations:
- https://github.com/webpro/release-it/blob/master/README.md
- https://medium.com/@webprolific/using-release-it-60b96515c073#.tv2lagbs2
- https://github.com/geddski/grunt-release
- https://github.com/RomanGotsiy/branch-release
- https://github.com/semantic-release/semantic-release
- https://github.com/vojtajina/grunt-bump/blob/master/tasks/bump.js

Docs:
- https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by micmro** [comment]
I've added a new task to clean up old files: just run `grunt clean:legacy` in your environment (you will need to `npm install` first)
